# Generated by Django 4.0.2 on 2022-10-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateLimit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('stun', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('lastTry', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
