# Generated by Django 4.0.7 on 2023-07-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ratelimit_setting_rate_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lastTry',
            new_name='last_try',
        ),
        migrations.AddField(
            model_name='setting',
            name='total_requests',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='student',
            name='total_tries',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
