# Generated by Django 4.0.7 on 2023-07-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_setting_total_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_tries',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
